From openjdk:8
copy ./target/spring-boot-angular-example-0.0.1-SNAPSHOT.jar spring-boot-angular-example-0.0.1-SNAPSHOT.jar
expose 8090
CMD ["java","-jar","spring-boot-angular-example-0.0.1-SNAPSHOT.jar"]